name: CI

on:
  push:
    branches: $default-branch
  pull_request: {}

env:
  NODE_VERSION: 12

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint and tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}

      # https://github.com/lirantal/lockfile-lint
      - name: Lint lockfile
        run: >
          npm_config_yes=true npx lockfile-lint
          --path yarn.lock
          --allowed-hosts npm yarn
          --validate-https

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn run lint

      - name: Run Tests
        run: yarn run test:ember

  floating:
    name: Floating Dependencies
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install --no-lockfile --non-interactive

      - name: Run Tests
        run: yarn run test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-classic
          - ember-default-with-jquery
          - embroider-safe
          - embroider-optimized

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
