# GitHub Actions documentation:
# https://docs.github.com/en/actions

name: Auto-update list of contributors

on:
  workflow_call:

    # https://github.com/akhilmhdh/contributors-readme-action#optional-parameters
    inputs:
      use_username:
        description: If people should be listed with their username instead of their full name.
        default: true
        required: false
        type: boolean

jobs:
  update_contributors_list:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      # https://github.com/akhilmhdh/contributors-readme-action
      - name: Update the list of contributors in the README file
        uses: akhilmhdh/contributors-readme-action@v2.3.2
        id: update_contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: auto-update contributors list (GH Action)'
          committer_username: 'akhilmhdh/contributors-readme-action'
          pr_title_on_protected: Auto-update list of contributors
          use_username: ${{ inputs.use_username }}

      # The previous step might have created a PR to make the update.
      # If that's the case, we want to close any previous similar PR, to avoid duplication.
      - name: 'Close previous pull request (if it exists)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          request="$( \
            gh api search/issues \
              --method GET \
              --raw-field q='repo:${{ github.repository }} type:pr state:open sort:updated-asc "Auto-update list of contributors" in:title' \
          )"

          count_pr=$( jq '.total_count' <<< $request )

          # We are supposed to have either 1 or 2 PRs:
          # - One PR:  1 created by the previous step + no existing PR
          # - Two PRs: 1 created by the previous step + 1 existing PR
          if [ $count_pr -eq 2 ]; then

            # PRs are sorted by least recently updated date => the first is the oldest.
            id_pr_oldest=$( jq '.items[0].number' <<< $request )

            # Comment the oldest PR with a link to the new PR.
            gh pr comment $id_pr_oldest \
              --repo ${{ github.repository }} \
              --body "Replaced by #${{ steps.update_contributors.outputs.pr_id }} ."

            # And finally, close the PR.
            gh pr close $id_pr_oldest \
              --repo ${{ github.repository }} \
              --delete-branch

          fi
